//
//  RocketsWorker.swift
//  CleanSpaceXApp
//
//  Created by Kurtuluş Ahmet TEMEL on 18.04.2020.
//  Copyright (c) 2020 Kurtuluş Ahmet TEMEL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CNetwork

class RocketsWorker {
    func fetchRockets(completion: @escaping ((_ response: [RocketsResponseModel], _ error: CNetworkError?) -> Void)) {
        CNetwork.shared.execute(requestRoute: CNetworkRouter.rockets, responseModel: [RocketsResponseModel].self) { result in
            switch result {
            case .success(let rockets):
                completion(rockets, nil)
            case .failure(let error):
                completion([], error)
            }
        }
    }
}
