//
//  RocketDetailWorker.swift
//  CleanSpaceXApp
//
//  Created by Kurtuluş Ahmet TEMEL on 18.04.2020.
//  Copyright (c) 2020 Kurtuluş Ahmet TEMEL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CNetwork

class RocketDetailWorker {
    var rocketStore: RocketStoreProtocol
    
    init(rocketStore: RocketStoreProtocol) {
      self.rocketStore = rocketStore
    }
    
    func fetchRocket(request: RocketDetail.FetchRocket.Request, completion: @escaping ((_ response: RocketsResponseModel?, _ error: CNetworkError?) -> Void)) {
        self.rocketStore.fetchRocket(request: request) { (rocket, error) in
            if error != nil {
                completion(nil, error)
            } else {
                completion(rocket, nil)
            }
        }
    }
}
