//
//  RocketDetailPresenter.swift
//  CleanSpaceXApp
//
//  Created by Kurtuluş Ahmet TEMEL on 18.04.2020.
//  Copyright (c) 2020 Kurtuluş Ahmet TEMEL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailPresentationLogic {
    func presentRocket(response: RocketDetail.FetchRocket.Response)
}

class RocketDetailPresenter: RocketDetailPresentationLogic {
    weak var viewController: RocketDetailDisplayLogic?
    
    // MARK: Present Rocket
    func presentRocket(response: RocketDetail.FetchRocket.Response) {
        let displayedRocket = RocketDetail.FetchRocket.ViewModel.DisplayedRocket(rocketName: response.rocket.rocketName, rocketDescription: response.rocket.rocketDescription, rocketImage: response.rocket.flickrImages.first ?? "https://unsplash.com/photos/woWf_VJ7dNs")
        
        let viewModel = RocketDetail.FetchRocket.ViewModel(displayedRocket: displayedRocket)
        viewController?.displayFetchedRocket(viewModel: viewModel)
    }
}
