//
//  RocketDetailInteractor.swift
//  CleanSpaceXApp
//
//  Created by Kurtuluş Ahmet TEMEL on 18.04.2020.
//  Copyright (c) 2020 Kurtuluş Ahmet TEMEL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailBusinessLogic {
    func fetchRocket(request: RocketDetail.FetchRocket.Request)
}

protocol RocketDetailDataStore {
    var rocket: RocketsResponseModel! { get set }
}

class RocketDetailInteractor: RocketDetailBusinessLogic, RocketDetailDataStore {
    var rocket: RocketsResponseModel!
    
    var presenter: RocketDetailPresentationLogic?
    var worker: RocketDetailWorker?
    
    // MARK: Fetch Rocket
    func fetchRocket(request: RocketDetail.FetchRocket.Request) {
        
        worker = RocketDetailWorker(rocketStore: RocketsAPI())
        var request = request
        request.rocketId = rocket.rocketID
        
        worker?.fetchRocket(request: request, completion: { (rocket, error) in
            if error != nil {
                //TODO: Bu kısımda hata mesajını ekranda göstermek için Clean Swift döngüsü çalıştırabilirsiniz.
            } else {
                if let rocket = rocket {
                    let response = RocketDetail.FetchRocket.Response(rocket: rocket)
                    self.presenter?.presentRocket(response: response)
                } else {
                    //TODO: Bu kısımda hata mesajını ekranda göstermek için Clean Swift döngüsü çalıştırabilirsiniz.
                }
            }
        })
    }
}
